{
	"version": 1584475295,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/player-sheet3.png",
		"images/ground-sheet0.png",
		"images/fruit-sheet0.png",
		"images/fruit-sheet1.png",
		"images/fruit-sheet2.png",
		"images/bplay-sheet0.png",
		"images/bg-sheet0.png",
		"images/logo-sheet0.png",
		"images/about-sheet0.png",
		"images/gamebg-sheet0.png",
		"images/enemy-sheet0.png",
		"media/hit1.m4a",
		"media/hit1.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}